version: '{build}'

image: Visual Studio 2019

install:
  - set SSL_CERT_FILE=C:/ruby24-x64/ssl/cert.pem
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - bundle install
build: off
test_script:
  - bundle exec rake test:all

environment:
  matrix:
    - ruby_version: "30-x64"
    - ruby_version: "30"
    - ruby_version: "27-x64"
    - ruby_version: "27"
    - ruby_version: "26-x64"
    - ruby_version: "26"
    - ruby_version: "25-x64"
    - ruby_version: "25"
    - ruby_version: "24-x64"
    - ruby_version: "24"
    - ruby_version: "23-x64"
    - ruby_version: "23"
    - ruby_version: "22-x64"
    - ruby_version: "22"
    - ruby_version: "21-x64"
    - ruby_version: "21"
    - ruby_version: "200-x64"
    - ruby_version: "200"
